### PR TITLE
new setup script for generic CPU/GPU ubuntu machines

### PR DESCRIPTION
**Pull request by mccrindlebrian**
Bash script to help facilitate setting up ubuntu machines.

### CODE REVIEW

**Comment by mccrindlebrian** [comment]
Related to https://github.com/opentensor/prompting/issues/81

**Review by schampoux — APPROVED** [review]

**Review by p-ferreira — APPROVED** [review]
LGTM

**Comment by p-ferreira** [comment]
@mccrindlebrian  What if we merge this into staging instead? I believe we will have another release before streaming/pre-staging

**Comment by mccrindlebrian** [comment]
@p-ferreira Fine with me

**Pull request merged**
