### PR TITLE
Add Chattensor System Prompt

### PR DESCRIPTION
**Pull request by bkb2135**
This adds the chattensor system prompt to reference generation to aid in the creation of an identity for the miners of SN1. Experiments are necessary to see the effects of the system prompt on the quality of references.

### CODE REVIEW

**Review by steffencruz — COMMENTED** [review]
If you take a look at my dev branch you'll see that I use this system prompt for all tasks that require generations.. this is just the first step.

**Comment by bkb2135** [comment]
That was what I saw and I wasn't too sure of the rationale behind it. Do we want the validators to have an idea of being "Chattensor" when they are generating challenges? It makes more sense to me that the challenge attempts to emulate a variety of humans, rather than being constrained to act like the idealized miner.

**Comment by p-ferreira** [comment]
Do we have any tests measuring in numbers the hallucination rate of this prompt and the reference text being used?
Is there any degradation in quality perceived? A good vibes check going through some generation samples would be interesting to ensure that the tasks don't lose much quality with this change

**Comment by bkb2135** [comment]
> Is there any degradation in quality perceived?

In the currently existing tasks, there was no change in rewards, and via manual inspection, the references appear not to have changed at all.

**Review by p-ferreira — APPROVED** [review]

**Pull request merged**
