### PR TITLE
V1.0.3 release

### PR DESCRIPTION
**Pull request by steffencruz**
Release branch for v1.0.3. Includes the following updates:
- **Generates validator reference** while waiting for dendrite responses, which speeds up validation by 40%
- Introduces **decaying scores** which punish miners who do not respond to all queries
- Introduces **preferential querying** of keys which do not share coldkeys or ips to prevent the same query from being sent multiple times to the same cabal (which creates repetition in responses)
- Minor readme and code **cleanup**
- **Unit tests** for concurrent generate and preferential querying
- Catch CUDA out of memory exceptions

### CODE REVIEW

**Comment by steffencruz** [comment]
Validator running current staging
https://wandb.ai/opentensor-dev/alpha-validators/runs/7cad6s7p/overview?workspace=user-

**Review by mccrindlebrian — APPROVED** [review]
LGTM!

**Comment by steffencruz** [comment]
Overnight tracked experiment as a last green light signal
https://wandb.ai/opentensor-dev/alpha-validators/runs/9lvl2m2c?workspace=user-opentensor-steffen

**Comment by steffencruz** [comment]
image
Speedup is not observed however this looks like it's just a slower machine (A6000 versus A100)

**Pull request merged**
