### PR TITLE
Logging/neuron info

### PR DESCRIPTION
**Pull request by steffencruz**
Adds richer logs for validator and miners (better than just a timestamp).

Also adds a step counter for miners so that they can see total requests served in logs.

### CODE REVIEW

**Review by schampoux — APPROVED** [review]
Looks good to me

**Review by p-ferreira — APPROVED** [review]
Just a small note, I believe that  it's a good practice initializing all the class attributes on init, even though python supports dynamic modifications of the instance such as the one implemented on `self.step`.

But that's just a suggestion, overall the PR looks ok

**Comment by steffencruz** [comment]
@p-ferreira not sure i understand. could you clarify or make a suggested change?

**Comment by p-ferreira** [comment]
> @p-ferreira not sure i understand. could you clarify or make a suggested change?

Ideally, class properties are initiated on `__init__`. This code sets the `self.step` property out of the init, profiting from the dynamic instance modification offered by python.

In bigger classes this can be a problem but since this use case is very specific, I think we are ok to leave it as it is, it was more of a suggestion for future implementations.

**Comment by steffencruz** [comment]
@p-ferreira the `BaseNeuron` class creates a step attribute for anything that subclasses it. This means that miners have have a step attribute since we released v1.0.0, we just never did anything with it. Does this address your question or am I still missing the point?

**Pull request merged**
